### ISSUE TITLE
Failed to load the unitjs package

### ISSUE THREAD

**Issue by vmptk** [unitjs/atom-unitjs#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [unitjs](https://github.com/unitjs/atom-unitjs) package, v0.2.0
### Stack Trace

Failed to load the unitjs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at Object.module.exports.extends (/home/venelin/.atom/packages/unitjs/node_modules/atom-helpers/lib/utils.js:25:26)
  at Object.<anonymous> (/home/venelin/.atom/packages/unitjs/lib/unitjs-view.js:21:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/venelin/.atom/packages/unitjs/lib/unitjs.js:9:18)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
  at /usr/share/atom/resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:451:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
  2x -2:37.1.0 window:toggle-full-screen (div.settings-view.pane-item)
     -1:24.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -0:36 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:29.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "exception-reporting"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-grails, v0.1.0
color-picker, v2.0.7
language-groovy, v0.4.0
minimap, v4.10.0
pigments, v0.8.0
react, v0.12.0
react-snippets, v0.1.4
unitjs, v0.2.0
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by Nicolab** [comment]
Fixed in v1.0.0

Thanks!
